FROM python:3-alpine

RUN apk add --no-cache git

WORKDIR /app

RUN git clone https://github.com/aboul3la/Sublist3r sublist3r

WORKDIR /app/sublist3r

RUN pip install -r requirements.txt \
    && chmod +x sublist3r.py

ENV PYTHONWARNINGS=ignore::SyntaxWarning
ENTRYPOINT ["python", "/app/sublist3r/sublist3r.py"]