FROM python:3-alpine

WORKDIR /app

RUN apk add --no-cache git
RUN git clone https://github.com/Arcanum-Sec/msftrecon.git

WORKDIR /app/msftrecon

RUN pip install -r requirements.txt \
    && chmod +x msftrecon/msftrecon.py

ENTRYPOINT ["python", "/app/msftrecon/msftrecon/msftrecon.py"]

