FROM python:3-alpine

WORKDIR /app

RUN apk add --no-cache git
RUN git clone https://github.com/0xZDH/Omnispray.git omnispray

WORKDIR /app/omnispray

RUN pip install -r requirements.txt \
    && chmod +x omnispray.py

ENV PYTHONWARNINGS=ignore::SyntaxWarning
ENTRYPOINT ["/app/omnispray/omnispray.py"]
CMD ["--help"]
